release-date = "2022-05-09"

[[entries]]
id = "2cbf8815-c21a-470b-9b0b-18f80d526995"
type = "feature"
description = "Add `Interpreter(enable_blocks, disable_blocks)` parameters"
author = "@NiklasRosenstein"

[[entries]]
id = "77a7da63-a630-48f9-a1b8-cf4a0b608e83"
type = "feature"
description = "Implement `Evaluator._eval_Array()` and `Evaluator._eval_Object()`"
author = "@NiklasRosenstein"
